# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faebeaf69f8c54bfffb29a712380f5cb995dbdd9b422a34af82c1aa4df965c7292c1e1e4e560a8d9002240621b5ba70e4641f53c25d2a41590198cb8eb4db9e6

test:
  secret_key_base: ba4c1e3788569402ab2198cfb5317af5859c3554b1627a19ee37d5bb6e4b7d1d77781d98b482e9a71b12adfe25636e0a96a7261f941599afb466a807374568f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
